name: Test ABI3 wheel in Python version

inputs:
  py-ver:
    description: "Python version"
    required: true

runs:
  using: "composite"
  steps:
  - name: Set up Python ${{ inputs.py-ver }}
    uses: actions/setup-python@v5
    with:
      python-version: ${{ inputs.py-ver }}
  - name: Run Python ${{ inputs.py-ver }}
    shell: bash
    run: |
      cd wheels
      ls -Al
      WHEEL=$(ls *.whl)
      python -m pip list
      python -m pip install $WHEEL
      python -m pip list
      python -m pip install pytest
      python -m pytest --pyargs abel --log-level=WARN
      python ../.github/workflows/save-test.py $WHEEL@${{ inputs.py-ver }}
