name: Action summary

on: workflow_dispatch

jobs:
  something:
    runs-on: ubuntu-latest
    steps:
    - name: Adding markdown
      run: |
        echo '### Hello world!' >> $GITHUB_STEP_SUMMARY
        echo '**bold**' >> $GITHUB_STEP_SUMMARY
        echo '*italic*' >> $GITHUB_STEP_SUMMARY
        echo '| Wheel | Pass | Error | Fail | Skip |' >> $GITHUB_STEP_SUMMARY
        echo '| --- | --- | --- | --- | --- |' >> $GITHUB_STEP_SUMMARY
        echo '| whl | **8** | 0 | 0 | 0 |' >> $GITHUB_STEP_SUMMARY
        echo '| broken-something-py123_armhf.whl | 6 | 0 | 0 | **2** |' >> $GITHUB_STEP_SUMMARY
        echo '| sdist | **6** | 0 | 0 | *2* |' >> $GITHUB_STEP_SUMMARY
