name: Test GitHub runs annotations

on: [workflow_dispatch, push]

jobs:
  wheels:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
    - run: echo '::notice::Test notice from echo'
    - run: python .github/workflows/annot.py
