name: Build package

on: workflow_dispatch

jobs:
  #sdist:
  #  uses: ./.github/workflows/sdist.yml

  #wheels:
  #  uses: ./.github/workflows/wheels.yml

  results:
    #needs: [sdist, wheels]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        sparse-checkout: .github/workflows/summary.yml
        sparse-checkout-cone-mode: false
    - uses: ./.github/workflows/summary.yml
    - name: Pack
      run: |
        mkdir pkg
        cp -t pkg sdist/* wheels-*/*.whl
    - uses: actions/upload-artifact@v4
      with:
        name: package
        path: pkg/*
