name: Test conda

on: workflow_dispatch

jobs:
  arm64:
    runs-on: macos-latest
    steps:
    - name: Install Miniconda
      # see https://www.anaconda.com/docs/getting-started/miniconda/install#macos-2
      run: |
        mkdir -p ~/miniconda3
        curl https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-arm64.sh \
             -o ~/miniconda3/miniconda.sh
        bash ~/miniconda3/miniconda.sh -b -u -p ~/miniconda3
        rm ~/miniconda3/miniconda.sh
    - name: Initialize conda
      run: |
        source ~/miniconda3/bin/activate
        conda init --all
    - name: Install PyAbel
      run: |
        source ~/miniconda3/bin/activate
        conda install -q conda-forge::pyabel
    - name: Install pytest
      run: |
        source ~/miniconda3/bin/activate
        conda install -q conda-forge::pytest
    - name: Run PyAbel tests
      run: |
        source ~/miniconda3/bin/activate
        conda info -a
        conda list
        python -m pytest --pyargs abel
