name: Publish to (Test)PyPI

on:
  workflow_dispatch: # trigger manually to publish any branch/tag to TestPyPI
    inputs: # actions have no comment/description, so showing a useless "input"
      _unused:
        description: 'Test publishing to TestPyPI'
        type: choice
        options:
          - yes
  push: # triggered by "Publish release" on GitHub to publish it on PyPI
    tags:
    - 'v[0-9]+.*'

jobs:
  build:
    uses: ./.github/workflows/build.yml

  publish:
    needs: build
    runs-on: ubuntu-22.04
    environment: pypi
    permissions:
      id-token: write # required for Trusted Publishing
    env:
      PYPI_URL: >-
        ${{ github.event_name == 'workflow_dispatch' &&
            'https://test.pypi.org/p/' ||
            'https://pypi.org/p/' }}
    steps:
    - name: Download package
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh run download -R '${{ github.repository }}' \
                        -n 'package-${{ github.ref_name }}' \
                        -D dist
    - name: Publish to ${{ env.PYPI_URL }}
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: ${{ env.PYPI_URL }}
        verbose: true
