# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  pytest:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-13, macos-latest, windows-latest]
        python-version: ["3.7", "3.13"]
        exclude:
          - os: macos-latest
            python-version: "3.7" # not available
          - os: macos-13
            python-version: "3.13" # to save resources

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: "pip"
        cache-dependency-path: setup.py
    - name: Install pytest
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install pytest pytest-cov
    - name: Install PyAbel
      run: python -m pip install . -v
    - name: Information
      run: >
        python3 -c "import platform, sys, numpy, scipy;
        print('Platorm:', platform.platform());
        print('Python:', sys.version);
        print('NumPy:', numpy.version.full_version);
        print('SciPy:', scipy.version.full_version)"
    - name: Run tests
      run: |
        cd ..
        pytest -v --cov=abel --pyargs abel
