name: Release on TestPyPI

on:
  # trigger manually to release any branch/tag on TestPyPI
  workflow_dispatch:
    inputs:
      testpypi:
        description: 'Test release on TestPyPI'
        required: true
        default: 'yes'
        type: choice
        options:
          - yes
  # trigger automatically on version tag creation
  # (by "Publish release" on GitHub)
  push:
    tags:
    - 'v[0-9]+.*'

jobs:
  publish:
    runs-on: ubuntu-22.04
    environment: pypi
    #permissions:
    #  # required for Trusted Publishing
    #  id-token: write
    env:
      PYPI_URL: >-
        ${{ github.event_name == 'workflow_dispatch' &&
            'https://test.pypi.org/p/' ||
            'https://pypi.org/p/' }}
    steps:
    - name: Publish to ${{ env.PYPI_URL }}
      run: echo 'Using PyPI URL ${{ env.PYPI_URL }}'

    #- name: Download package
    #  run: |
    #    gh run download -R '${{ github.repository }}' \
    #                    -n 'package-${{ github.ref_name }}' \
    #                    -D dist
    #  env:
    #    GH_TOKEN: ${{ github.token }}
    #- name: Publish to TestPyPI
    #  uses: pypa/gh-action-pypi-publish@release/v1
    #  with:
    #    repository-url: https://test.pypi.org/legacy/
    #    verbose: true
