name: Release on TestPyPI

on:
  workflow_dispatch:

jobs:
  pypi-publish:
    runs-on: ubuntu-22.04
    environment: pypi
    permissions:
      # required for Trusted Publishing
      id-token: write
    steps:
    - name: Download package
      run: gh run download -n 'package-${{ github.ref_name }}' -D dist
      env:
        GH_TOKEN: ${{ github.token }}
    - name: Publish to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
        verbose: true
