name: Build sdist

on: workflow_dispatch

jobs:
  sdist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12" # only for setuptools
      - name: Update setup
        run: python -m pip install --upgrade pip setuptools
      - name: Create source distribution
        run: python setup.py sdist
      - uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: ./dist/*

  sdist-tests:
    needs: sdist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: sdist
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install PyAbel from source distribution
        run: pip install -v *
      - name: Install pytest
        run: pip install pytest
      - name: Run tests
        run: pytest -v --pyargs abel
