name: Builds summary

on: workflow_dispatch

env:
  GH_TOKEN: ${{ github.token }} # for "gh run download"

jobs:
  summary:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        sparse-checkout: .github/workflows/summary.py
        sparse-checkout-cone-mode: false
    - run: gh run download -p 'sdist*' -p 'wheels-*'
    - run: ls -AlR
    - run: cp -t . sdist-*/*.xml wheels-*/*.xml
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Summary
      run: python .github/workflows/summary.py
