name: Test wheels

on: workflow_dispatch

jobs:
  wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04]

    steps:
    - uses: actions/checkout@v4
      with:
        sparse-checkout: .github/workflows/testabi3wheel/action.yml
        sparse-checkout-cone-mode: false
    - run: echo Test > test.txt
    - run: ls -RAl
    - name: Test with Python 3.11
      uses: ./.github/workflows/testabi3wheel
      with:
        py-ver: "3.11"
    - name: Test with Python 3.12
      uses: ./.github/workflows/testabi3wheel
      with:
        py-ver: "3.12"
