name: Test wheels

on: workflow_dispatch

jobs:
  wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04]

    steps:
    - uses: actions/checkout@v4
      with:
        sparse-checkout: .github/workflows/testabi3wheel
    - run: ls -RAl
    - uses: ./.github/workflows/testabi3wheel
      with:
        py-ver: "3.11"
    - uses: ./.github/workflows/testabi3wheel
      with:
        py-ver: "3.12"
