name: Build wheels

on: [workflow_dispatch, workflow_call]

jobs:
  wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]#, macos-13, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12" # for cibuildwheel itself
    - name: Install cibuildwheel
      run: python -m pip install cibuildwheel==2.22.0
    - name: Build wheels
      env:
        # build only for Python versions with full support
        CIBW_PROJECT_REQUIRES_PYTHON: ">=3.12"
      run: python -m cibuildwheel --output-dir wheels
    - uses: actions/upload-artifact@v4
      with:
        name: wheels-${{ github.ref_name }}-${{ matrix.os }}
        path: ./wheels/*
