name: Build wheels

on: workflow_dispatch

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]#, macos-13, macos-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: "3.12" # for cibuildwheel itself
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.22.0
      - name: Build wheels
        env:
          CIBW_PROJECT_REQUIRES_PYTHON: ">=3.12" # limit to full-support
          CIBW_TEST_REQUIRES: pytest
          CIBW_TEST_COMMAND: "python -m pytest --pyargs abel"
        run: python -m cibuildwheel --output-dir wheels
      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheels/*.whl
